spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      enabled: true
      max-file-size: 256MB
      max-request-size: 256MB
  application:
    name: dynamic-pdf-generator

#  main:
#    allow-bean-definition-overriding: true
